### ISSUE TITLE
Categorical.Laws

### ISSUE THREAD

**Issue by conal** [conal/denotational-hardware#4]
Fill in `Categorical.Laws`.

**Comment by bolt12** [comment]
There's still more to be done, even with #7 merged!

**Comment by conal** [comment]
Our friend @jwiegley developed an extensive [category theory library for Coq](https://github.com/jwiegley/category-theory). I'd love to get his expert input on the laws for `Cartesian` and `CartesianClosed` and later for monoidal variants.

**Comment by conal** [comment]
`Cartesian` and `CartesianClosed` in progress in PR #13.

**Comment by conal** [comment]
Closed by PR #13.
